# Generated by Django 3.1.3 on 2020-11-20 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CareTaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('username', models.CharField(blank=True, max_length=150, null=True)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GrandParent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('phone', models.CharField(blank=True, default='', max_length=17)),
                ('greeting_message', models.CharField(default='', max_length=256)),
                ('care_taker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grandparent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('shape', models.CharField(max_length=15)),
                ('color', models.CharField(max_length=15)),
                ('size', models.CharField(max_length=10)),
                ('remaining', models.IntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pill', to='remempill.grandparent')),
            ],
        ),
        migrations.CreateModel(
            name='PillConsumption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_to_consume', models.DateTimeField(blank=True, null=True)),
                ('consumed', models.BooleanField(default=False)),
                ('pill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pill_consumption', to='remempill.pill')),
            ],
        ),
    ]
